# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "SecureChatGuide.org"
name                     : "Supernova"
title_separator          : "-"
description              : "Guides and reviews of secure encrypted messaging apps for Android, iOS, Mac, Windows and Linux"
url                      : https://securechatguide.org
# enforce_ssl:             : securechatguide.org
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : Perelandra0x309/secure-im # GitHub username/repo-name
include: ['_pages']
class_button_internal: 'class="w3-blue w3-round-large " style="border:none;display:inline-block;padding:8px 16px;vertical-align:middle;overflow:hidden;text-decoration:none;color:inherit;background-color:inherit;text-align:center;cursor:pointer;"'
class_button_external: 'class="w3-btn w3-green w3-round-large"'
