# Template:
#- name: 
#  category: (1- P2P open source, 2- P2P closed source, 3- Other open source, 4- Other closed source)
#  display_name: 
#  url: 
#  recommendation: (1- highly, 2- worth a try, 3- not recommended)
#  platforms: Android/iOS/Mac/Windows/Linux
#  communication_types: 
#  country_origin: 
#  requires_phone_number: Yes/No
#  requires_email: Yes/No
#  android_requires_google_play: Yes/No
#  is_locally_encrypted: Yes/No
#  perfect_forward_secrecy: Yes/No
#  websites: 
#  notes_file: 

#  Category 1- P2P open source

- name: ricochet
  category: 1
  display_name: Ricochet
  url: https://ricochet.im
  recommendation: 1
  platforms: <a href="https://ricochet.im/releases/latest/">Windows, Mac, Linux</a>
  communication_types: Text
  country_origin: No centralized servers
  requires_phone_number: Not applicable
  requires_email: No
  android_requires_google_play: Not applicable
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/ricochet-im/ricochet">Source Code</a>
  notes_file: ricochet_notes.html

- name: tox
  category: 1
  display_name: Tox
  url: https://tox.chat/
  recommendation: 1
  platforms: <a href="https://tox.chat/download.html">Windows, Mac, Linux, FreeBSD, iOS, Android</a>
  communication_types: Text, voice, video, screen sharing, file sharing
  country_origin: No centralized servers
  requires_phone_number: No
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/TokTok/c-toxcore">toxcore source</a>
  notes_file: tox_notes.html
  
- name: ring
  category: 1
  display_name: Ring
  url: https://ring.cx
  recommendation: 2
  platforms: <a href="https://ring.cx/en/download">Android, Linux, Mac, Windows (soon iOS)</a>
  communication_types: Text, group chat, voice, video
  country_origin: Canada
  requires_phone_number: No
  requires_email:
  android_requires_google_play:
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/savoirfairelinux/">Source Code</a>
  notes_file: ring_notes.html
  
- name: briar
  category: 1
  display_name: Briar Project
  url: https://briarproject.org
  recommendation: 2
  platforms: Android (doesn't need play services) via Google Play, <a href="https://briarproject.org/fdroid.html">F-Droid repo</a> or <a href="https://briarproject.org/apk.html">APK</a>
  communication_types: Text and forums
  country_origin:
  requires_phone_number:
  requires_email:
  android_requires_google_play: No
  is_locally_encrypted:
  perfect_forward_secrecy:
  websites: <a href="https://code.briarproject.org/akwizgran/briar/tree/master">Source Code</a>
  notes_file: briar_notes.html
  
# Category 2- P2P closed source

- name: safeswiss
  category: 2
  display_name: SafeSwiss
  url: https://safeswiss.com
  recommendation: 1
  platforms: Android, iOS, Windows
  communication_types: Text, group chat, voice, pictures, video, location
  country_origin: Switzerland (<a href="https://lu.chregister.ch/cr-portal/auszug/auszug.xhtml;?uid=CHE-141.225.695">Company Register</a>)
  requires_phone_number: No
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: Yes
  websites: <a href="https://safeswiss.com/encryption">Encryption</a>
  notes_file: safeswiss_notes.html

- name: twinme
  category: 2
  display_name: TwinMe
  url: https://twin.me
  recommendation: 1
  platforms: Android, iOS
  communication_types: Text, voice, video
  country_origin: France?
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: Yes
  websites: <a href="https://twin.me/en/support/twinme-protect-data/">Encryption</a>
  notes_file: twinme_notes.html

- name: sid
  category: 2
  display_name: Sid
  url: https://sid.co
  recommendation: 1
  platforms: Android, iOS, Mac, Windows, Linux
  communication_types: Text, group chat, pictures, audio, files
  country_origin: Germany
  requires_phone_number: No
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://sid.co/security-by-design">Security by Design</a>
  notes_file: sid_notes.html

- name: stealthchat
  category: 2
  display_name: StealthChat
  url: http://stealthchat.com
  recommendation: 2
  platforms: Android, iOS
  communication_types: Text, voice, pictures
  country_origin: USA
  requires_phone_number: Yes
  requires_email: No
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: 
  notes_file: stealthchat_notes.html

- name: kripter
  category: 2
  display_name: Kripter
  url: https://kripter.io
  recommendation: 3
  platforms: Android
  communication_types: Text, voice, pictures, files, location
  country_origin: 
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: 
  notes_file: kripter_notes.html

# Category 3- Other open source

- name: signal
  category: 3
  display_name: Signal
  url: https://www.signal.org
  recommendation: 1
  platforms: Android (<a href="https://signal.org/android/apk/">Direct APK download</a>), iPhone, Desktop
  communication_types: Text, voice, video, files, images
  country_origin:
  requires_phone_number: Yes
  requires_email:
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy:
  websites: <a href="https://github.com/WhisperSystems">Source Code</a>, <a href="https://www.signal.org/docs/">Technical docs</a>
  notes_file: signal_notes.html
  
- name: xmpp
  category: 3
  display_name: XMPP with OTR or OMEMO
  url: https://xmpp.org
  recommendation: 1
  platforms: Android, iOS, Mac, Windows, Linux
  communication_types: Text, group chat
  country_origin: 
  requires_phone_number: No
  requires_email: Yes
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: Yes
  websites: <a href="https://xmpp.org/getting-started/">Getting Started</a>
  notes_file: xmpp_notes.html

- name: keybase
  category: 3
  display_name: Keybase
  url: https://www.keybase.io
  recommendation: 1
  platforms: Android, iOS, Mac, Windows, Linux
  communication_types: Text, group chat, file sharing
  country_origin: USA
  requires_phone_number: No
  requires_email: Yes
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: No
  websites: <a href="https://github.com/keybase">Source code</a>
  notes_file: keybase_notes.html

- name: riot
  category: 3
  display_name: Riot
  url: https://about.riot.im
  recommendation: 1
  platforms: Android, iOS, Mac, Windows, Linux, Web
  communication_types: Text, voice, video, file sharing
  country_origin: 
  requires_phone_number: No
  requires_email: Yes
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/vector-im">Source code</a>
  notes_file: riot_notes.html

- name: tor_messenger
  category: 3
  display_name: Tor Messenger
  url: https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger
  recommendation: 1
  platforms: Mac, Windows, Linux
  communication_types: Text
  country_origin: 
  requires_phone_number: No
  requires_email: No
  android_requires_google_play: N/A
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: 
  notes_file: tormessenger_notes.html

- name: kontalk
  category: 3
  display_name: Kontalk (XMPP)
  url: http://www.kontalk.org
  recommendation: 2
  platforms: Android, Java client
  communication_types: Text
  country_origin: 
  requires_phone_number: Yes
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://github.com/kontalk/desktopclient-java">Java Client source</a>, <a href="https://github.com/kontalk/androidclient">Android client source</a>
  notes_file: kontalk_notes.html

- name: retroshare
  category: 3
  display_name: RetroShare
  url: http://retroshare.net
  recommendation: 2
  platforms: <a href="http://retroshare.net/downloads.html">Windows, Mac, Linux</a>
  communication_types: Text, voice, video, email, file sharing
  country_origin: 
  requires_phone_number: No
  requires_email: 
  android_requires_google_play: N/A
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://github.com/RetroShare/RetroShare">Source code</a>
  notes_file: retroshare_notes.html

- name: wire
  category: 3
  display_name: Wire
  url: https://wire.com
  recommendation: 3
  platforms: Android, iOS, Mac, Windows, Linux, Web
  communication_types: Text, voice, video
  country_origin: 
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://github.com/wireapp">Source code</a>
  notes_file: wire_notes.html

- name: surespot
  category: 3
  display_name: Surespot
  url: https://www.surespot.me
  recommendation: 2
  platforms: Android, iOS
  communication_types: Text, voice, images
  country_origin: 
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://github.com/surespot">Source code</a>
  notes_file: surespot_notes.html

# Category 4- Other closed source

- name: threema
  category: 4
  display_name: Threema
  url: https://threema.ch
  recommendation: 1
  platforms: Android, iOS, Windows Phone, Web
  communication_types: Text, group chat, voice, files
  country_origin: Switzerland
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: No
  websites: <a href="https://threema.ch/press-files/cryptography_whitepaper.pdf">Cryptography Whitepaper</a>
  notes_file: threema_notes.html

- name: eleet
  category: 4
  display_name: Eleet
  url: https://eleet.im
  recommendation: 1
  platforms: <a href="https://eleet.im/download/#tap-mobile">Android, iOS</a>, <a href="https://eleet.im/download/#tab-desktop">MacOS, Windows, Linux</a>, <a href="https://eleet.im/download/#tap-web">Web</a>
  communication_types: Text, group chat, photos, videos, audio files
  country_origin: Scotland, UK
  requires_phone_number: No
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: Yes
  websites: 
  notes_file: eleet_notes.html

- name: wickrme
  category: 4
  display_name: Wickr Me
  url: https://www.wickr.com/personal
  recommendation: 2
  platforms: <a href="https://me-download.wickr.com/#/version/me">Android, iOS, MacOS, Windows, Ubuntu</a>
  communication_types: Text, group chat, video, files
  country_origin: USA
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/WickrInc/wickr-crypto-c">Secure Messaging Protocol source</a>
  notes_file: wickrme_notes.html

- name: vipole
  category: 4
  display_name: VIPole
  url: https://www.vipole.com
  recommendation: 2
  platforms: <a href="https://www.vipole.com/en/download">Android, iOS, Mac, Windows, Linux</a>
  communication_types: Text, files, photos, video, location, contacts, audio
  country_origin: UK
  requires_phone_number: No
  requires_email: 
  android_requires_google_play: No
  is_locally_encrypted: No (free version)
  perfect_forward_secrecy: Yes
  websites: <a href="https://www.vipole.com/en/security/encryption">Encryption</a>
  notes_file: vipole_notes.html

- name: hoccer
  category: 4
  display_name: Hoccer
  url: https://hoccer.com
  recommendation: 2
  platforms: <a href="https://hoccer.com/#section-download">Android, iOS</a>
  communication_types: Text, file sharing
  country_origin: Germany
  requires_phone_number: Yes
  requires_email: 
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://hoccer.com/faq/">FAQ</a>
  notes_file: hoccer_notes.html

- name: simsme
  category: 4
  display_name: SIMSme
  url: https://www.sims.me
  recommendation: 2
  platforms: <a href="https://www.sims.me/en#Download">Android, iOS</a>
  communication_types: Text, group chat, images, videos, location, contacts
  country_origin: Germany
  requires_phone_number: Yes
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://www.sims.me/data-protection">Data Protection</a>
  notes_file: simsme_notes.html

- name: securechat
  category: 4
  display_name: GDATA Secure Chat
  url: https://www.gdata.de/mobile
  recommendation: 2
  platforms: Android
  communication_types: Text, voice, photos
  country_origin: Germany
  requires_phone_number: Yes
  requires_email: No
  android_requires_google_play: Yes
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: 
  notes_file: securechat_notes.html

- name: cypher
  category: 4
  display_name: Goldenfrog Cypher
  url: https://www.goldenfrog.com/cyphr
  recommendation: 3
  platforms: Android, iOS
  communication_types: Text, group chat, pictures
  country_origin: Switzerland
  requires_phone_number: No
  requires_email: Yes
  android_requires_google_play: No
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://www.goldenfrog.com/cyphr/how-cyphr-works">How Cypher Works</a>
  notes_file: cypher_notes.html

- name: telegram
  category: 4
  display_name: Telegram
  url: https://telegram.org
  recommendation: 3
  platforms: <a href="https://telegram.org/apps">Android, iOS, Windows, MacOS, web</a>
  communication_types: Text, voice, file sharing
  country_origin: First Russia, now Dubai
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://telegram.org/faq#q-how-secure-is-telegram">Security</a>
  notes_file: telegram_notes.html

- name: viber
  category: 4
  display_name: Viber
  url: https://www.viber.com
  recommendation: 3
  platforms: Android, iOS, Mac, Windows, Linux
  communication_types: Text, group messaging, voice and video calls, photos
  country_origin: 
  requires_phone_number: Yes
  requires_email: No
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://support.viber.com">Support</a>, <a href="https://www.viber.com/security-overview">Security Overview</a>
  notes_file: viber_notes.html

- name: confide
  category: 4
  display_name: Confide
  url: https://getconfide.com
  recommendation: 3
  platforms: <a href="https://getconfide.com/download">Android, iOS, Mac, Windows</a>
  communication_types: Text, group messaging, voice and video messages, file sharing
  country_origin: 
  requires_phone_number: 
  requires_email: 
  android_requires_google_play: 
  is_locally_encrypted: 
  perfect_forward_secrecy: 
  websites: <a href="https://getconfide.com/faq">FAQ</a>, <a href="https://static.getconfide.com/audits/Confide-PT_A4.ENG.0001.02.pdf">Security Audit</a>
  notes_file: confide_notes.html
