# Template:
#- name:
#  category: (1- P2P open source, 2- P2P closed source, 3- Other open source, 4- Other closed source)
#  display_name:
#  url:
#  recommendation: (1- highly, 2- worth a try, 3- not recommended)
#  platforms:
#  communication_types:
#  country_origin:
#  requires_phone_number:
#  requires_email:
#  android_requires_google_play:
#  is_locally_encrypted:
#  perfect_forward_secrecy:
#  websites:
#  notes_file:

- name: ricochet
  category: 1
  display_name: Ricochet
  url: https://ricochet.im
  recommendation: 1
  platforms: <a href="https://ricochet.im/releases/latest/">Windows, Mac, Linux</a>
  communication_types: Text
  country_origin: "?"
  requires_phone_number: Not applicable
  requires_email: No
  android_requires_google_play: Not applicable
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/ricochet-im/ricochet">Source Code</a>
  notes_file: ricochet_notes.html

- name: tox
  category: 1
  display_name: Tox
  url: https://tox.chat/
  recommendation: 1
  platforms: <a href="https://tox.chat/download.html">Windows, Mac, Linux, FreeBSD, iOS, Android</a>
  communication_types: Text, voice, video, screen sharing, file sharing
  country_origin:
  requires_phone_number: No
  requires_email: No
  android_requires_google_play: No
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/TokTok/c-toxcore">toxcore source</a>
  notes_file: tox_notes.html
  
- name: ring
  category: 1
  display_name: Ring
  url: https://ring.cx
  recommendation: 2
  platforms: <a href="https://ring.cx/en/download">Android, Linux, Mac, Windows (soon iOS)</a>
  communication_types: Text, group chat, voice, video
  country_origin: Canada
  requires_phone_number: No
  requires_email:
  android_requires_google_play:
  is_locally_encrypted:
  perfect_forward_secrecy: Yes
  websites: <a href="https://github.com/savoirfairelinux/">Source Code</a>
  notes_file: ring_notes.html
  
- name: briar
  category: 1
  display_name: Briar Project
  url: https://briarproject.org
  recommendation: 2
  platforms: Android (doesn't need play services) via Google Play, <a href="https://briarproject.org/fdroid.html">F-Droid repo</a> or <a href="https://briarproject.org/apk.html">APK</a>
  communication_types: Text and forums
  country_origin:
  requires_phone_number:
  requires_email:
  android_requires_google_play: No
  is_locally_encrypted:
  perfect_forward_secrecy:
  websites: <a href="https://code.briarproject.org/akwizgran/briar/tree/master">Source Code</a>
  notes_file: briar_notes.html
  
- name: signal
  category: 3
  display_name: Signal
  url: https://www.signal.org
  recommendation: 1
  platforms: Android (<a href="https://signal.org/android/apk/">Direct APK download</a>), iPhone, Desktop
  communication_types: Text, voice, video, files, images
  country_origin:
  requires_phone_number: Yes
  requires_email:
  android_requires_google_play: No
  is_locally_encrypted: Yes
  perfect_forward_secrecy:
  websites: <a href="https://github.com/WhisperSystems">Source Code</a>, <a href="https://www.signal.org/docs/">Technical docs</a>
  notes_file: signal_notes.html
  
